---
default:
  name : qwinixqa6
  email : qwinixqa6@yopmail.com
  username : qwinixqa6
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

common_user:
  username : qwinixqa5
  password : Qwinix1

common_user1:
  username : qwinixqa6
  password : Qwinix1

admin:
  username : Tombarron
  password : Password1