---
default:
  name : qwinixqa413
  email : qwinixqa413@yopmail.com
  username : qwinixqa413
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

second_aa_user:
  name : qwinixqa414
  email : qwinixqa414@yopmail.com
  username : qwinixqa414
  password : Qwinix1
  ph_no : 1236549870
  city : abcd
  state : Colorado
  title : Relationship Manager

normal_user:
  name : cucumber15
  email : cucumber15@yopmail.com
  username : cucumber15
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

# common_user:
#   username : qwinixqa15
#   password : Qwinix1

# common_user1:
#   username : qwinixqa16
#   password : Qwinix1

admin:
  username : Tombarron
  password : Password1

linkedin:
  email : cucumberwatir@gmail.com
  password : Qwinix1234
