---
default:
  name : qwinixqa2
  email : qwinixqa2@yopmail.com
  username : qwinixqa2
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

common_user:
  username : qwinixqa2
  password : Qwinix1

admin:
  username : Tombarron
  password : Password1




