---
default:
  name : qwinixqa3
  email : qwinixqa3@yopmail.com
  username : qwinixqa3
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

common_user:
  username : qwinixqa3
  password : Qwinix1

admin:
  username : Tombarron
  password : Password1