---
default:
  name : qwinixqa11
  email : qwinixqa11@yopmail.com
  username : qwinixqa11
  password : Qwinix1
  ph_no : 1234567890
  city : abcd
  state : Indiana
  title : Lender

common_user:
  username : qwinixqa5
  password : Qwinix1

common_user1:
  username : qwinixqa6
  password : Qwinix1

admin:
  username : Tombarron
  password : Password1

linkedin:
  email : cucumberwatir@gmail.com
  password : Qwinix1234